const text = `Apollo 11 was the spaceflight that first landed humans on the moon. 
           Neil Armstrong and Buzz Aldrin formed the American crew that landed the Apollo 
           Lunar Module Eagle on July 20, 1969, at 20:17 UTC. Armstrong became the first person 
           to step onto the lunar surface, Aldrin joined him 19 minutes later.`;

const items = [
  {
    key: 1,
    date: '20 July 1969',
    status: 'Sold',
    title: 'First man on the moon',
    category: 'History',
    text,
    price: '299.49 HSY',
  },
  {
    key: 2,
    date: '21 July 1969',
    status: 'Sold',
    title: 'First man on the moon',
    category: 'History',
    text,
    price: '299.49 HSY',
  },
  {
    key: 3,
    date: '22 July 1969',
    status: 'Sold',
    title: 'First man on the moon',
    category: 'History',
    text,
    price: '299.49 HSY',
  },
  {
    key: 4,
    date: '23 July 1969',
    status: 'Sold',
    title: 'First man on the moon',
    category: 'History',
    text,
    price: '299.49 HSY',
  },
  {
    key: 5,
    date: '24 July 1969',
    status: 'Sold',
    title: 'First man on the moon',
    category: 'History',
    text,
    price: '299.49 HSY',
  },
  {
    key: 6,
    date: '25 July 1969',
    status: 'Sold',
    title: 'First man on the moon',
    category: 'History',
    text,
    price: '299.49 HSY',
  },
  {
    key: 7,
    date: '26 July 1969',
    status: 'Sold',
    title: 'First man on the moon',
    category: 'History',
    text,
    price: '299.49 HSY',
  },
  {
    key: 8,
    date: '27 July 1969',
    status: 'Sold',
    title: 'First man on the moon',
    category: 'History',
    text,
    price: '299.49 HSY',
  },
  {
    key: 9,
    date: '28 July 1969',
    status: 'Sold',
    title: 'First man on the moon',
    category: 'History',
    text,
    price: '299.49 HSY',
  },
  {
    key: 10,
    date: '29 July 1969',
    status: 'Sold',
    title: 'First man on the moon',
    category: 'History',
    text,
    price: '299.49 HSY',
  },
  {
    key: 11,
    date: '30 July 1969',
    status: 'Sold',
    title: 'First man on the moon',
    category: 'History',
    text,
    price: '299.49 HSY',
  },
  {
    key: 12,
    date: '31 July 1969',
    status: 'Sold',
    title: 'First man on the moon',
    category: 'History',
    text,
    price: '299.49 HSY',
  },
];

export { items };
